dns:
  links:
    - rule: https://raw.githubusercontent.com/yettera765/scripts/main/ruleset/dns.list
    - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Telegram/TelegramUS.list
unbreak:
  links:
    - rule: https://raw.githubusercontent.com/yettera765/scripts/main/ruleset/ntp.list
    - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Unbreak.list
block:
  links:
    - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Privacy.list
    - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Hijacking.list
    - rule: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    - rule: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
    - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Advertising.list
    - rule: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
    - domain: https://justdomains.github.io/blocklists/lists/nocoin-justdomains.txt
proxy:
  noip: true
  links:
    - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Global.list
    - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Streaming.list
    - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Apple/Apple.list
    - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Google/GoogleVoice.list
    - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Microsoft/OneDrive.list
    - rule: https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Twitch.list
    - rule: https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Spotify.list
direct:
  noip: true
  links:
    - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/China.list
    - rule: https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic.list
    - rule: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    - ip: https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt
