unbreak:
  - rule: https://raw.githubusercontent.com/yettera765/scripts/main/ruleset/high-prior.list
  - rule: https://raw.githubusercontent.com/yettera765/scripts/main/ruleset/ntp.list
  - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Unbreak.list
block:
  - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Privacy.list
  - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Hijacking.list
  - rule: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list 
  - rule: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
  - rule: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
block-lite:
  - rule: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
  - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Privacy.list
  - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Hijacking.list
  - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Advertising.list
proxy:
  - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Global.list
  - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/StreamingMedia/Streaming.list
direct:
  - rule: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/China.list
  - rule: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
